services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - back
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network      

  back:
    build: 
      context: ./back
      target: prod
    ports:
      - "5000:5000"
    restart: always
    env_file: 
      - .env
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/back"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network 

  mongo:
    image: mongo:7.0
    volumes:
      - mongoDb:/data/db
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

volumes:
  mongoDb:

networks:
  app-network:
    driver: bridge